services:
  # --- Infrastructure ---
  notif-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/bastien-antigravity/notif-server:${TAG:-latest}
    container_name: notif-server
    restart: unless-stopped
    ports:
      - "${NT_IP:-127.0.0.1}:${NT_PORT:-1026}:${NT_PORT:-1026}"
      - "${NT_GRPC_IP:-127.0.0.1}:${NT_GRPC_PORT:-1027}:${NT_GRPC_PORT:-1027}"
      - "${NT_REST_IP:-127.0.0.1}:${NT_REST_PORT:-1029}:${NT_REST_PORT:-1029}"
    networks:
      - teleremote-network
    labels: [ com.centurylinklabs.watchtower.enable=true ]

networks:
  teleremote-network:
    name: teleremote-network
    external: true
