// Code generated by capnpc-go. DO NOT EDIT.

package capnp_notifier

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
)

type NotifierMsg capnp.Struct

// NotifierMsg_TypeID is the unique identifier for the type NotifierMsg.
const NotifierMsg_TypeID = 0x868758ad9f398b4f

func NewNotifierMsg(s *capnp.Segment) (NotifierMsg, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NotifierMsg(st), err
}

func NewRootNotifierMsg(s *capnp.Segment) (NotifierMsg, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return NotifierMsg(st), err
}

func ReadRootNotifierMsg(msg *capnp.Message) (NotifierMsg, error) {
	root, err := msg.Root()
	return NotifierMsg(root.Struct()), err
}

func (s NotifierMsg) String() string {
	str, _ := text.Marshal(0x868758ad9f398b4f, capnp.Struct(s))
	return str
}

func (s NotifierMsg) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NotifierMsg) DecodeFromPtr(p capnp.Ptr) NotifierMsg {
	return NotifierMsg(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NotifierMsg) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NotifierMsg) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NotifierMsg) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NotifierMsg) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NotifierMsg) Message_() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NotifierMsg) HasMessage_() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NotifierMsg) Message_Bytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NotifierMsg) SetMessage_(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s NotifierMsg) Attachment() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s NotifierMsg) HasAttachment() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s NotifierMsg) AttachmentBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s NotifierMsg) SetAttachment(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s NotifierMsg) Tags() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(2)
	if err != nil {
		return capnp.TextList{}, err
	}
	l, err := p.ListDefault(x_cd0e7dad96752db7[0:40])
	return capnp.TextList(l), err
}

func (s NotifierMsg) HasTags() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s NotifierMsg) SetTags(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(2, v.ToPtr())
}

// NewTags sets the tags field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s NotifierMsg) NewTags(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(2, l.ToPtr())
	return l, err
}

// NotifierMsg_List is a list of NotifierMsg.
type NotifierMsg_List = capnp.StructList[NotifierMsg]

// NewNotifierMsg creates a new list of NotifierMsg.
func NewNotifierMsg_List(s *capnp.Segment, sz int32) (NotifierMsg_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[NotifierMsg](l), err
}

// NotifierMsg_Future is a wrapper for a NotifierMsg promised by a client call.
type NotifierMsg_Future struct{ *capnp.Future }

func (f NotifierMsg_Future) Struct() (NotifierMsg, error) {
	p, err := f.Future.Ptr()
	return NotifierMsg(p.Struct()), err
}

const schema_cd0e7dad96752db7 = "x\xda,\xc9\xbdJ\x03A\x14\xc5\xf1s\xeel\x14d" +
	"\x1d\xbd\xb0O!D\xb0\xd4*\x08\x82\x8a\x1f;\xa0 " +
	"vC\x18\xd7@v\x0d\xceXX\x88\x9d\x16\xf6\xb6>" +
	"A\xb0\xb4\xb4\xb2\x11R\xf8D#\xd1T\x87\xf3\xff\xad" +
	"\xdf\x0f\x8a\xad\xd5OB\\\xd5[\xca\xa7/\xdbo\xd3" +
	"\x8b\xe7'\xa8e\xfe\xe8\xdf\xbdN\x1f\xec\x0c=\xb3\x0c" +
	"\xe8\xd7\xb7\xfe\xccw\xf6\x8e~\xeen\xd2\xe8j\x146" +
	"e\xe8'\xddd\xe7\xe4\xff\x1e\xc7\x06\xa8IW\x9a\x02" +
	"(\x08\xe8\xde.\xe0\x06\x86\xeeH\xa8dE\x92zp" +
	"\x09\xb8}Cw&T\x91\x8aB\xea\xf9\x06\xe0jC" +
	"7\x16>\xb6!F\xdf\x04\x96\x10\x96`\xf6)\xf9\xe1" +
	"u\x1b`\xba\xb4\x88P\xae\x00k\xc97\x91\x16\xac\x0d" +
	"\xff\xc0\xce\xc1*\x0fs\x0a\xe3\xd0\xdc\xfa\x16\xc0o\x00" +
	"\x00\x00\xff\xffgH1\x83"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_cd0e7dad96752db7,
		Nodes: []uint64{
			0x868758ad9f398b4f,
		},
		Compressed: true,
	})
}

var x_cd0e7dad96752db7 = []byte{
	0, 0, 0, 0, 4, 0, 0, 0,
	1, 0, 0, 0, 14, 0, 0, 0,
	1, 0, 0, 0, 74, 0, 0, 0,
	116, 101, 108, 101, 103, 114, 97, 109,
	0, 0, 0, 0, 0, 0, 0, 0,
}
