// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: notif_server.proto

package grpc_control

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_notif_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{0}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ControlResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *ControlResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

// -----------------------------------------------------------------------------
// Notifier Management
type ListNotifiersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifiersRequest) Reset() {
	*x = ListNotifiersRequest{}
	mi := &file_notif_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifiersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifiersRequest) ProtoMessage() {}

func (x *ListNotifiersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifiersRequest.ProtoReflect.Descriptor instead.
func (*ListNotifiersRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{1}
}

type NotifierInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifierInfo) Reset() {
	*x = NotifierInfo{}
	mi := &file_notif_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifierInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifierInfo) ProtoMessage() {}

func (x *NotifierInfo) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifierInfo.ProtoReflect.Descriptor instead.
func (*NotifierInfo) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{2}
}

func (x *NotifierInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NotifierInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotifierInfo) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

type ListNotifiersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Notifiers     []*NotifierInfo        `protobuf:"bytes,2,rep,name=notifiers,proto3" json:"notifiers,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotifiersResponse) Reset() {
	*x = ListNotifiersResponse{}
	mi := &file_notif_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotifiersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotifiersResponse) ProtoMessage() {}

func (x *ListNotifiersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotifiersResponse.ProtoReflect.Descriptor instead.
func (*ListNotifiersResponse) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{3}
}

func (x *ListNotifiersResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ListNotifiersResponse) GetNotifiers() []*NotifierInfo {
	if x != nil {
		return x.Notifiers
	}
	return nil
}

func (x *ListNotifiersResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SendTestNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"` // INFO, WARNING, ERROR, CRITICAL
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTestNotificationRequest) Reset() {
	*x = SendTestNotificationRequest{}
	mi := &file_notif_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTestNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTestNotificationRequest) ProtoMessage() {}

func (x *SendTestNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTestNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendTestNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{4}
}

func (x *SendTestNotificationRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *SendTestNotificationRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SendTestNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReloadConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadConfigRequest) Reset() {
	*x = ReloadConfigRequest{}
	mi := &file_notif_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadConfigRequest) ProtoMessage() {}

func (x *ReloadConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadConfigRequest.ProtoReflect.Descriptor instead.
func (*ReloadConfigRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{5}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_notif_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{6}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Details       map[string]string      `protobuf:"bytes,5,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_notif_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *GetStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetStatusResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetStatusResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetStatusResponse) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// -----------------------------------------------------------------------------
// Alerting Configuration
type GetAlertingConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertingConfigRequest) Reset() {
	*x = GetAlertingConfigRequest{}
	mi := &file_notif_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingConfigRequest) ProtoMessage() {}

func (x *GetAlertingConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingConfigRequest.ProtoReflect.Descriptor instead.
func (*GetAlertingConfigRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{8}
}

type AlertingConfigSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      map[string]string      `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlertingConfigSection) Reset() {
	*x = AlertingConfigSection{}
	mi := &file_notif_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlertingConfigSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertingConfigSection) ProtoMessage() {}

func (x *AlertingConfigSection) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertingConfigSection.ProtoReflect.Descriptor instead.
func (*AlertingConfigSection) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{9}
}

func (x *AlertingConfigSection) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

type GetAlertingConfigResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Success       bool                              `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Config        map[string]*AlertingConfigSection `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // platform -> settings
	Timestamp     int64                             `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlertingConfigResponse) Reset() {
	*x = GetAlertingConfigResponse{}
	mi := &file_notif_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlertingConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlertingConfigResponse) ProtoMessage() {}

func (x *GetAlertingConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlertingConfigResponse.ProtoReflect.Descriptor instead.
func (*GetAlertingConfigResponse) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{10}
}

func (x *GetAlertingConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetAlertingConfigResponse) GetConfig() map[string]*AlertingConfigSection {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *GetAlertingConfigResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type SetAlertingConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlertingConfigRequest) Reset() {
	*x = SetAlertingConfigRequest{}
	mi := &file_notif_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlertingConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlertingConfigRequest) ProtoMessage() {}

func (x *SetAlertingConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlertingConfigRequest.ProtoReflect.Descriptor instead.
func (*SetAlertingConfigRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{11}
}

func (x *SetAlertingConfigRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *SetAlertingConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SetAlertingConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type AddProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddProviderRequest) Reset() {
	*x = AddProviderRequest{}
	mi := &file_notif_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddProviderRequest) ProtoMessage() {}

func (x *AddProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddProviderRequest.ProtoReflect.Descriptor instead.
func (*AddProviderRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{12}
}

func (x *AddProviderRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AddProviderRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type RemoveProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveProviderRequest) Reset() {
	*x = RemoveProviderRequest{}
	mi := &file_notif_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveProviderRequest) ProtoMessage() {}

func (x *RemoveProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveProviderRequest.ProtoReflect.Descriptor instead.
func (*RemoveProviderRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveProviderRequest) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type GetSupportedTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedTypesRequest) Reset() {
	*x = GetSupportedTypesRequest{}
	mi := &file_notif_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedTypesRequest) ProtoMessage() {}

func (x *GetSupportedTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedTypesRequest.ProtoReflect.Descriptor instead.
func (*GetSupportedTypesRequest) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{14}
}

type GetSupportedTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Types         []string               `protobuf:"bytes,2,rep,name=types,proto3" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSupportedTypesResponse) Reset() {
	*x = GetSupportedTypesResponse{}
	mi := &file_notif_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSupportedTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupportedTypesResponse) ProtoMessage() {}

func (x *GetSupportedTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notif_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupportedTypesResponse.ProtoReflect.Descriptor instead.
func (*GetSupportedTypesResponse) Descriptor() ([]byte, []int) {
	return file_notif_server_proto_rawDescGZIP(), []int{15}
}

func (x *GetSupportedTypesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSupportedTypesResponse) GetTypes() []string {
	if x != nil {
		return x.Types
	}
	return nil
}

var File_notif_server_proto protoreflect.FileDescriptor

const file_notif_server_proto_rawDesc = "" +
	"\n" +
	"\x12notif_server.proto\x12\fgrpc_control\"\x82\x01\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"\x16\n" +
	"\x14ListNotifiersRequest\"P\n" +
	"\fNotifierInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\"\x89\x01\n" +
	"\x15ListNotifiersResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x128\n" +
	"\tnotifiers\x18\x02 \x03(\v2\x1a.grpc_control.NotifierInfoR\tnotifiers\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"c\n" +
	"\x1bSendTestNotificationRequest\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x15\n" +
	"\x13ReloadConfigRequest\"\x12\n" +
	"\x10GetStatusRequest\"\x81\x02\n" +
	"\x11GetStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12F\n" +
	"\adetails\x18\x05 \x03(\v2,.grpc_control.GetStatusResponse.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1a\n" +
	"\x18GetAlertingConfigRequest\"\xa3\x01\n" +
	"\x15AlertingConfigSection\x12M\n" +
	"\bsettings\x18\x01 \x03(\v21.grpc_control.AlertingConfigSection.SettingsEntryR\bsettings\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x02\n" +
	"\x19GetAlertingConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12K\n" +
	"\x06config\x18\x02 \x03(\v23.grpc_control.GetAlertingConfigResponse.ConfigEntryR\x06config\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x1a^\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x129\n" +
	"\x05value\x18\x02 \x01(\v2#.grpc_control.AlertingConfigSectionR\x05value:\x028\x01\"^\n" +
	"\x18SetAlertingConfigRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\":\n" +
	"\x12AddProviderRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\")\n" +
	"\x15RemoveProviderRequest\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\"\x1a\n" +
	"\x18GetSupportedTypesRequest\"K\n" +
	"\x19GetSupportedTypesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05types\x18\x02 \x03(\tR\x05types2\xbf\x06\n" +
	"\x13NotifControlService\x12X\n" +
	"\rListNotifiers\x12\".grpc_control.ListNotifiersRequest\x1a#.grpc_control.ListNotifiersResponse\x12`\n" +
	"\x14SendTestNotification\x12).grpc_control.SendTestNotificationRequest\x1a\x1d.grpc_control.ControlResponse\x12P\n" +
	"\fReloadConfig\x12!.grpc_control.ReloadConfigRequest\x1a\x1d.grpc_control.ControlResponse\x12L\n" +
	"\tGetStatus\x12\x1e.grpc_control.GetStatusRequest\x1a\x1f.grpc_control.GetStatusResponse\x12d\n" +
	"\x11GetAlertingConfig\x12&.grpc_control.GetAlertingConfigRequest\x1a'.grpc_control.GetAlertingConfigResponse\x12Z\n" +
	"\x11SetAlertingConfig\x12&.grpc_control.SetAlertingConfigRequest\x1a\x1d.grpc_control.ControlResponse\x12N\n" +
	"\vAddProvider\x12 .grpc_control.AddProviderRequest\x1a\x1d.grpc_control.ControlResponse\x12T\n" +
	"\x0eRemoveProvider\x12#.grpc_control.RemoveProviderRequest\x1a\x1d.grpc_control.ControlResponse\x12d\n" +
	"\x11GetSupportedTypes\x12&.grpc_control.GetSupportedTypesRequest\x1a'.grpc_control.GetSupportedTypesResponseB\x12Z\x10src/grpc_controlb\x06proto3"

var (
	file_notif_server_proto_rawDescOnce sync.Once
	file_notif_server_proto_rawDescData []byte
)

func file_notif_server_proto_rawDescGZIP() []byte {
	file_notif_server_proto_rawDescOnce.Do(func() {
		file_notif_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notif_server_proto_rawDesc), len(file_notif_server_proto_rawDesc)))
	})
	return file_notif_server_proto_rawDescData
}

var file_notif_server_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_notif_server_proto_goTypes = []any{
	(*ControlResponse)(nil),             // 0: grpc_control.ControlResponse
	(*ListNotifiersRequest)(nil),        // 1: grpc_control.ListNotifiersRequest
	(*NotifierInfo)(nil),                // 2: grpc_control.NotifierInfo
	(*ListNotifiersResponse)(nil),       // 3: grpc_control.ListNotifiersResponse
	(*SendTestNotificationRequest)(nil), // 4: grpc_control.SendTestNotificationRequest
	(*ReloadConfigRequest)(nil),         // 5: grpc_control.ReloadConfigRequest
	(*GetStatusRequest)(nil),            // 6: grpc_control.GetStatusRequest
	(*GetStatusResponse)(nil),           // 7: grpc_control.GetStatusResponse
	(*GetAlertingConfigRequest)(nil),    // 8: grpc_control.GetAlertingConfigRequest
	(*AlertingConfigSection)(nil),       // 9: grpc_control.AlertingConfigSection
	(*GetAlertingConfigResponse)(nil),   // 10: grpc_control.GetAlertingConfigResponse
	(*SetAlertingConfigRequest)(nil),    // 11: grpc_control.SetAlertingConfigRequest
	(*AddProviderRequest)(nil),          // 12: grpc_control.AddProviderRequest
	(*RemoveProviderRequest)(nil),       // 13: grpc_control.RemoveProviderRequest
	(*GetSupportedTypesRequest)(nil),    // 14: grpc_control.GetSupportedTypesRequest
	(*GetSupportedTypesResponse)(nil),   // 15: grpc_control.GetSupportedTypesResponse
	nil,                                 // 16: grpc_control.GetStatusResponse.DetailsEntry
	nil,                                 // 17: grpc_control.AlertingConfigSection.SettingsEntry
	nil,                                 // 18: grpc_control.GetAlertingConfigResponse.ConfigEntry
}
var file_notif_server_proto_depIdxs = []int32{
	2,  // 0: grpc_control.ListNotifiersResponse.notifiers:type_name -> grpc_control.NotifierInfo
	16, // 1: grpc_control.GetStatusResponse.details:type_name -> grpc_control.GetStatusResponse.DetailsEntry
	17, // 2: grpc_control.AlertingConfigSection.settings:type_name -> grpc_control.AlertingConfigSection.SettingsEntry
	18, // 3: grpc_control.GetAlertingConfigResponse.config:type_name -> grpc_control.GetAlertingConfigResponse.ConfigEntry
	9,  // 4: grpc_control.GetAlertingConfigResponse.ConfigEntry.value:type_name -> grpc_control.AlertingConfigSection
	1,  // 5: grpc_control.NotifControlService.ListNotifiers:input_type -> grpc_control.ListNotifiersRequest
	4,  // 6: grpc_control.NotifControlService.SendTestNotification:input_type -> grpc_control.SendTestNotificationRequest
	5,  // 7: grpc_control.NotifControlService.ReloadConfig:input_type -> grpc_control.ReloadConfigRequest
	6,  // 8: grpc_control.NotifControlService.GetStatus:input_type -> grpc_control.GetStatusRequest
	8,  // 9: grpc_control.NotifControlService.GetAlertingConfig:input_type -> grpc_control.GetAlertingConfigRequest
	11, // 10: grpc_control.NotifControlService.SetAlertingConfig:input_type -> grpc_control.SetAlertingConfigRequest
	12, // 11: grpc_control.NotifControlService.AddProvider:input_type -> grpc_control.AddProviderRequest
	13, // 12: grpc_control.NotifControlService.RemoveProvider:input_type -> grpc_control.RemoveProviderRequest
	14, // 13: grpc_control.NotifControlService.GetSupportedTypes:input_type -> grpc_control.GetSupportedTypesRequest
	3,  // 14: grpc_control.NotifControlService.ListNotifiers:output_type -> grpc_control.ListNotifiersResponse
	0,  // 15: grpc_control.NotifControlService.SendTestNotification:output_type -> grpc_control.ControlResponse
	0,  // 16: grpc_control.NotifControlService.ReloadConfig:output_type -> grpc_control.ControlResponse
	7,  // 17: grpc_control.NotifControlService.GetStatus:output_type -> grpc_control.GetStatusResponse
	10, // 18: grpc_control.NotifControlService.GetAlertingConfig:output_type -> grpc_control.GetAlertingConfigResponse
	0,  // 19: grpc_control.NotifControlService.SetAlertingConfig:output_type -> grpc_control.ControlResponse
	0,  // 20: grpc_control.NotifControlService.AddProvider:output_type -> grpc_control.ControlResponse
	0,  // 21: grpc_control.NotifControlService.RemoveProvider:output_type -> grpc_control.ControlResponse
	15, // 22: grpc_control.NotifControlService.GetSupportedTypes:output_type -> grpc_control.GetSupportedTypesResponse
	14, // [14:23] is the sub-list for method output_type
	5,  // [5:14] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_notif_server_proto_init() }
func file_notif_server_proto_init() {
	if File_notif_server_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notif_server_proto_rawDesc), len(file_notif_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notif_server_proto_goTypes,
		DependencyIndexes: file_notif_server_proto_depIdxs,
		MessageInfos:      file_notif_server_proto_msgTypes,
	}.Build()
	File_notif_server_proto = out.File
	file_notif_server_proto_goTypes = nil
	file_notif_server_proto_depIdxs = nil
}
