// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: notif_server.proto

package grpc_control

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NotifControlService_ListNotifiers_FullMethodName        = "/grpc_control.NotifControlService/ListNotifiers"
	NotifControlService_SendTestNotification_FullMethodName = "/grpc_control.NotifControlService/SendTestNotification"
	NotifControlService_ReloadConfig_FullMethodName         = "/grpc_control.NotifControlService/ReloadConfig"
	NotifControlService_GetStatus_FullMethodName            = "/grpc_control.NotifControlService/GetStatus"
	NotifControlService_GetAlertingConfig_FullMethodName    = "/grpc_control.NotifControlService/GetAlertingConfig"
	NotifControlService_SetAlertingConfig_FullMethodName    = "/grpc_control.NotifControlService/SetAlertingConfig"
	NotifControlService_AddProvider_FullMethodName          = "/grpc_control.NotifControlService/AddProvider"
	NotifControlService_RemoveProvider_FullMethodName       = "/grpc_control.NotifControlService/RemoveProvider"
	NotifControlService_GetSupportedTypes_FullMethodName    = "/grpc_control.NotifControlService/GetSupportedTypes"
)

// NotifControlServiceClient is the client API for NotifControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NotifControlServiceClient interface {
	// Notifier Management
	ListNotifiers(ctx context.Context, in *ListNotifiersRequest, opts ...grpc.CallOption) (*ListNotifiersResponse, error)
	SendTestNotification(ctx context.Context, in *SendTestNotificationRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// Server Status
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Alerting Configuration
	GetAlertingConfig(ctx context.Context, in *GetAlertingConfigRequest, opts ...grpc.CallOption) (*GetAlertingConfigResponse, error)
	SetAlertingConfig(ctx context.Context, in *SetAlertingConfigRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	AddProvider(ctx context.Context, in *AddProviderRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	RemoveProvider(ctx context.Context, in *RemoveProviderRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	GetSupportedTypes(ctx context.Context, in *GetSupportedTypesRequest, opts ...grpc.CallOption) (*GetSupportedTypesResponse, error)
}

type notifControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNotifControlServiceClient(cc grpc.ClientConnInterface) NotifControlServiceClient {
	return &notifControlServiceClient{cc}
}

func (c *notifControlServiceClient) ListNotifiers(ctx context.Context, in *ListNotifiersRequest, opts ...grpc.CallOption) (*ListNotifiersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNotifiersResponse)
	err := c.cc.Invoke(ctx, NotifControlService_ListNotifiers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) SendTestNotification(ctx context.Context, in *SendTestNotificationRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, NotifControlService_SendTestNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) ReloadConfig(ctx context.Context, in *ReloadConfigRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, NotifControlService_ReloadConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, NotifControlService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) GetAlertingConfig(ctx context.Context, in *GetAlertingConfigRequest, opts ...grpc.CallOption) (*GetAlertingConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlertingConfigResponse)
	err := c.cc.Invoke(ctx, NotifControlService_GetAlertingConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) SetAlertingConfig(ctx context.Context, in *SetAlertingConfigRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, NotifControlService_SetAlertingConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) AddProvider(ctx context.Context, in *AddProviderRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, NotifControlService_AddProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) RemoveProvider(ctx context.Context, in *RemoveProviderRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, NotifControlService_RemoveProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *notifControlServiceClient) GetSupportedTypes(ctx context.Context, in *GetSupportedTypesRequest, opts ...grpc.CallOption) (*GetSupportedTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSupportedTypesResponse)
	err := c.cc.Invoke(ctx, NotifControlService_GetSupportedTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NotifControlServiceServer is the server API for NotifControlService service.
// All implementations must embed UnimplementedNotifControlServiceServer
// for forward compatibility.
type NotifControlServiceServer interface {
	// Notifier Management
	ListNotifiers(context.Context, *ListNotifiersRequest) (*ListNotifiersResponse, error)
	SendTestNotification(context.Context, *SendTestNotificationRequest) (*ControlResponse, error)
	ReloadConfig(context.Context, *ReloadConfigRequest) (*ControlResponse, error)
	// Server Status
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Alerting Configuration
	GetAlertingConfig(context.Context, *GetAlertingConfigRequest) (*GetAlertingConfigResponse, error)
	SetAlertingConfig(context.Context, *SetAlertingConfigRequest) (*ControlResponse, error)
	AddProvider(context.Context, *AddProviderRequest) (*ControlResponse, error)
	RemoveProvider(context.Context, *RemoveProviderRequest) (*ControlResponse, error)
	GetSupportedTypes(context.Context, *GetSupportedTypesRequest) (*GetSupportedTypesResponse, error)
	mustEmbedUnimplementedNotifControlServiceServer()
}

// UnimplementedNotifControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNotifControlServiceServer struct{}

func (UnimplementedNotifControlServiceServer) ListNotifiers(context.Context, *ListNotifiersRequest) (*ListNotifiersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListNotifiers not implemented")
}
func (UnimplementedNotifControlServiceServer) SendTestNotification(context.Context, *SendTestNotificationRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendTestNotification not implemented")
}
func (UnimplementedNotifControlServiceServer) ReloadConfig(context.Context, *ReloadConfigRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReloadConfig not implemented")
}
func (UnimplementedNotifControlServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedNotifControlServiceServer) GetAlertingConfig(context.Context, *GetAlertingConfigRequest) (*GetAlertingConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlertingConfig not implemented")
}
func (UnimplementedNotifControlServiceServer) SetAlertingConfig(context.Context, *SetAlertingConfigRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAlertingConfig not implemented")
}
func (UnimplementedNotifControlServiceServer) AddProvider(context.Context, *AddProviderRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProvider not implemented")
}
func (UnimplementedNotifControlServiceServer) RemoveProvider(context.Context, *RemoveProviderRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProvider not implemented")
}
func (UnimplementedNotifControlServiceServer) GetSupportedTypes(context.Context, *GetSupportedTypesRequest) (*GetSupportedTypesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSupportedTypes not implemented")
}
func (UnimplementedNotifControlServiceServer) mustEmbedUnimplementedNotifControlServiceServer() {}
func (UnimplementedNotifControlServiceServer) testEmbeddedByValue()                             {}

// UnsafeNotifControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NotifControlServiceServer will
// result in compilation errors.
type UnsafeNotifControlServiceServer interface {
	mustEmbedUnimplementedNotifControlServiceServer()
}

func RegisterNotifControlServiceServer(s grpc.ServiceRegistrar, srv NotifControlServiceServer) {
	// If the following call panics, it indicates UnimplementedNotifControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NotifControlService_ServiceDesc, srv)
}

func _NotifControlService_ListNotifiers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNotifiersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).ListNotifiers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_ListNotifiers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).ListNotifiers(ctx, req.(*ListNotifiersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_SendTestNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTestNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).SendTestNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_SendTestNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).SendTestNotification(ctx, req.(*SendTestNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_ReloadConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReloadConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).ReloadConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_ReloadConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).ReloadConfig(ctx, req.(*ReloadConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_GetAlertingConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlertingConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).GetAlertingConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_GetAlertingConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).GetAlertingConfig(ctx, req.(*GetAlertingConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_SetAlertingConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAlertingConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).SetAlertingConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_SetAlertingConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).SetAlertingConfig(ctx, req.(*SetAlertingConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_AddProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).AddProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_AddProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).AddProvider(ctx, req.(*AddProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_RemoveProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).RemoveProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_RemoveProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).RemoveProvider(ctx, req.(*RemoveProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NotifControlService_GetSupportedTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSupportedTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotifControlServiceServer).GetSupportedTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NotifControlService_GetSupportedTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotifControlServiceServer).GetSupportedTypes(ctx, req.(*GetSupportedTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NotifControlService_ServiceDesc is the grpc.ServiceDesc for NotifControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NotifControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grpc_control.NotifControlService",
	HandlerType: (*NotifControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNotifiers",
			Handler:    _NotifControlService_ListNotifiers_Handler,
		},
		{
			MethodName: "SendTestNotification",
			Handler:    _NotifControlService_SendTestNotification_Handler,
		},
		{
			MethodName: "ReloadConfig",
			Handler:    _NotifControlService_ReloadConfig_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _NotifControlService_GetStatus_Handler,
		},
		{
			MethodName: "GetAlertingConfig",
			Handler:    _NotifControlService_GetAlertingConfig_Handler,
		},
		{
			MethodName: "SetAlertingConfig",
			Handler:    _NotifControlService_SetAlertingConfig_Handler,
		},
		{
			MethodName: "AddProvider",
			Handler:    _NotifControlService_AddProvider_Handler,
		},
		{
			MethodName: "RemoveProvider",
			Handler:    _NotifControlService_RemoveProvider_Handler,
		},
		{
			MethodName: "GetSupportedTypes",
			Handler:    _NotifControlService_GetSupportedTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "notif_server.proto",
}
